import type { Metadata } from 'next'
import './globals.css'
import { quicksand } from '@/components/fonts'
import Header from '@/components/header'
import Footer from '@/components/footer'
import { SessionProvider } from 'next-auth/react'

export const metadata: Metadata = {
  title: 'Movies',
  description: 'Generated by create next app'
}
export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`w-screen overflow-x-hidden ${quicksand.className}   antialiased  `}
      >
        <SessionProvider>
          <Header />
          {children}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  )
}
