import type { Metadata } from 'next'
import './globals.css'
import { quicksand } from '@/components/fonts'

export const metadata: Metadata = {
  title: 'Movies',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={quicksand.className}>{children}</body>
    </html>
  )
}
